name: pure_dart_ui
description: Some classes from `dart.ui` that run on pure Dart without depending on the Flutter SDK.
version: 0.1.0
repository: https://github.com/signmotion/pure_dart_ui.git

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
