name: pure_dart_ui
description: >-
  The classes and functions from dart:ui that works on all platforms:
  Color, Offset, Rect, Size, etc.
repository: https://github.com/signmotion/pure_dart_ui.git
topics:
  - pure-dart
  - ui
  - geometry
  - color
  - rectangle

# Compatible with https://semver.org
# Format:
#   version: major.minor.patch
# You can calculate the number version code by this formula:
#   code = m[A]jor * 100 * 100 + m[I]nor * 100 + [P]atch
# Otherwise: +AAIIPP
version: 0.1.8

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.4
