name: pure_dart_ui
description: The classes from `dart.ui` that run on pure Dart without depending on the Flutter SDK.
repository: https://github.com/signmotion/pure_dart_ui.git

topics:
  - pure-dart
  - ui
  - geometry
  - color
  - rectangle

# Format:
#   version: major.minor.patch
# You can calculate the number version code by this formula:
#   code = m[A]jor * 100 * 100 + m[I]nor * 100 + [P]atch
# Otherwise: +AAIIPP
version: 0.1.4

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
